# This file is **NOT** a standard Jekyll config file. 
# 
# It is used to define default config options for this theme.
# These settings will be merged with site specific settings at runtime, site specific settings override these defaults.

# Additional config options are defined using the Jekyll Data plugin, under the `site.data.bsk_jekyll_vars` namespace.
# E.g. `site.data.bsk_jekyll_vars.bsk_attributes.bsk_version` gives the version of the BAS Style Kit this theme uses.

# Plugins (required by this theme)
#

plugins:
  - jekyll-data

# Build settings
#

# Set default permalink format
permalink: pretty

# Site settings
#

# Set default layout - the empty `path` acts as a wildcard targetting all files in the site
defaults:
  -
    scope:
      path: ""
    values:
      layout: "bas-style-kit/bsk--standard"
