# This file **is** a standard Jekyll config file. 
#
# It is used to test the components that make up the BAS Style Kit Jekyll Theme works as expected, it does not test the
# theme itself (i.e. in terms of treating includes as 'theme' includes, rather than 'site' includes, and config merging)

# Plugins
#

plugins:
  - jekyll-menus
  - jekyll-tidy

# Build settings
#

markdown: kramdown
# - normally this would be 'jekyll-theme-bas-style-kit' but this *is* that theme so that won't work
theme: !!null

# This wouldn't normally be necessary as the site would be contained in a `site` sub-directory or similar
exclude:
  - Gemfile
  - Gemfile.lock
  - CHANGELOG.md
  - CONTRIBUTING.md
  - LICENSE-MIT.md
  - LICENSE.md
  - README.md	
  - Dockerfile
  - docker-compose.yml
  - jekyll-theme-bas-style-kit.gemspec
  - screenshot.png
  - docs
  - tests

# Server settings
#

host: 0.0.0.0
port: 9000
encoding: UTF-8

# Site settings
#

# e.g. /foo
baseurl: ''

collections:
  tests:
    output: true

# Theme settings
#

# This is a copy of the settings defined in `_config.yml` 
# as this file isn't loaded when the theme is being tested internally
bas_style_kit_jekyll_theme:
  feature_flags:
    site:
      back_to_top_anchor: true
      standard_header: true
      standard_footer: true
    standard_header:
      cookie_notice: true
      site_navigation: true
      development_phase: true
    standard_footer:
      is_something_wrong: true
      back_to_top: true
      spacer: false
      divider: true
      governance: true
      legal_policies: true
    page:
      toc: true
  attributes: 
    container: 'fixed'
    head_title:
      # Used when `page.title` isn't set
      default: 'BAS Style Kit Jekyll Theme'
      # Appended to either `page.title` or `head_title.default` - e.g. ` - Site Foo`
      appended: ' - BAS Style Kit Jekyll Theme' 
    head_description: 'Jekyll theme implementation of the BAS Style Kit - https://stlye-kit.web.bas.ac.uk.'
    site_brand:
      text: 'BAS Style Kit Jekyll Theme'
      href: '/'
    site_development_phase: 'alpha'
    site_feedback_href: '#'
    site_analytics: 
      id: 'UA-64130716-27'
    site_styles: []
    site_scripts: []

    # These settings aren't usually changed
    head_favicon: 'data:;base64,iVBORw0KGgo='
    site_back_to_top_target_href: '#site-top'
    site_footer:
      ogl:
        href: 'http://www.nationalarchives.gov.uk/doc/open-government-licence'
        text_version: 'v3.0'
      legal_policies:
        copyright_href: '#'
        cookies_href: '#'
        privacy_href: '#'
