# This file is **NOT** a standard Jekyll config file. 
# 
# It is used to define default config options for this theme.
# These settings will be merged with site specific settings at runtime, site specific settings override these defaults.

# Additional config options are defined using the Jekyll Data plugin, under the `site.data.bsk_jekyll_vars` namespace.
# E.g. `site.data.bsk_jekyll_vars.bsk_attributes.bsk_version` gives the version of the BAS Style Kit this theme uses.

# Plugins (required by this theme)
#

plugins:
  - jekyll-data

# Build settings
#

# Set default permalink format
permalink: pretty

# Site settings
#

# Set default layout - the empty `path` acts as a wildcard targetting all files in the site
defaults:
  -
    scope:
      path: ''
    values:
      layout: 'bas-style-kit/bsk--standard'

# Theme settings
#

bas_style_kit_jekyll_theme:
  attributes:
    container: fixed

    head_title:
      # Used when `page.title` isn't set
      default: 'site title'
      # Appended to either `page.title` or `head_title.default` - e.g. `- Site Foo`
      appended: !!null

    head_description: 'site description'

    site_brand:
        text: 'site title'
        img: !!null
        img_size: !!null
        href: '/'
      
    site_development_phase: 'alpha'
    
    site_feedback_href: '#'

    site_analytics: 
      id: !!null

    # These settings aren't usually changed
    head_description: 'data:;base64,iVBORw0KGgo='
    site_back_to_top_target_href: '#site-top'
    site_footer:
      ogl:
        href: 'http://www.nationalarchives.gov.uk/doc/open-government-licence'
        img: 'https://cdn.web.bas.ac.uk/bas-style-kit/0.3.0/img/logos-symbols/ogl-symbol-inverse-transparent-32.png'
        text_version: 'v3.0'
      legal_policies:
        copyright_href: '#'
        cookies_href: '#'
        privacy_href: '#'
  