# This file is **NOT** a standard Jekyll config file. 
# 
# It is used to define config options for use by the BAS Style Kit Jekyll Theme, which will be merged together with 
# individual website options at runtime using the Jekyll Data plugin.

# If any of these options are set within a site's config file, it will override the values defined here.

# Plugins (required by this theme)

gems:
  - jekyll-data

# Set default permalink format

permalink: pretty

# Set default development phase

phase: live

# Set default layout

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"

# Set default related sites

nav_related_sites:
  -
    name: BAS Home
    href: https://www.bas.ac.uk
  - 
    name: Discover BAS data
    href: https://data.bas.ac.uk
