# This file is **NOT** a standard Jekyll config file. 
# 
# It is used to define default config options for this theme.
# These settings will be merged with site specific settings at runtime, site specific settings override these defaults.

# Additional config options are defined using the Jekyll Data plugin, under the `site.data.bsk_jekyll_vars` namespace.
# E.g. `site.data.bsk_jekyll_vars.bsk_attributes.bsk_version` gives the version of the BAS Style Kit this theme uses.

# Plugins (required by this theme)
#

plugins:
  - jekyll-data
  - jekyll-tidy

# Build settings
#

# Set default permalink format
permalink: pretty

# Theme settings
#

bas_style_kit_jekyll_theme:
  feature_flags:
    site:
      back_to_top_anchor: true
      standard_header: true
      standard_footer: true
    standard_header:
      cookie_notice: true
      site_navigation: true
      development_phase: true
    standard_footer:
      is_something_wrong: true
      back_to_top: true
      spacer: false
      divider: true
      governance: true
      legal_policies: true
    page:
      toc: true
  attributes:
    container: fixed
    head_title:
      # Used when `page.title` isn't set
      default: 'site title'
      # Appended to either `page.title` or `head_title.default` - e.g. ` - Site Foo`
      appended: !!null
    head_description: 'site description'
    site_brand:
        text: 'site title'
        img: !!null
        img_size: !!null
        href: '/'
    site_development_phase: 'alpha'
    site_feedback_href: '/feedback.html'
    site_analytics: 
      id: !!null
    site_styles: []
    site_scripts: []

    # These settings aren't usually changed
    head_favicon: 'data:;base64,iVBORw0KGgo='
    site_back_to_top_target_href: '#site-top'
    site_footer:
      ogl:
        href: 'http://www.nationalarchives.gov.uk/doc/open-government-licence'
        text_version: 'v3.0'
      legal_policies:
        copyright_href: '/legal/copyright'
        cookies_href: '/legal/cookies'
        privacy_href: '/legal/privacy'
