---
version: '2'

services:
  app:
    build: .
    image: docker-registry.data.bas.ac.uk/web-apps/bsk/bas-style-kit-jekyll-theme:0.8.0-alpine
    volumes:
      - .:/usr/src/app
    ports:
      - "9000:9000"
