---
version: '2'

services:
  app:
    build: .
    image: docker-registry.data.bas.ac.uk/web-apps/bsk/bas-style-kit-jekyll-theme:0.3.0-alpine-develop
    volumes:
      - .:/usr/src/app
    ports:
      - "9000:9000"
    environment:
      - JEKYLL_ENV=development
